In [5]:
from classes.environments.PendulumSimple import PendulumSimple
from classes.agents.FD_LSVI import FD_LSVI
from functions.misc.test_algorithm_after_learning import test_algorithm

In [2]:
import numpy as np
env = PendulumSimple()
state_action = np.random.uniform(low=-1,high=1, size=(10,3))
print(state_action)
env.query_generator(state_action)

[[ 0.4275223   0.10837772 -0.92230561]
 [-0.92325245 -0.82683708  0.57424242]
 [ 0.49656464 -0.33970788 -0.02415646]
 [ 0.41208245 -0.63473114 -0.10671581]
 [-0.81061792 -0.59176689  0.05599515]
 [ 0.18912616  0.6022967   0.62750762]
 [-0.83924787 -0.46507372 -0.3753205 ]
 [-0.21406806  0.55008701  0.04655448]
 [-0.65418359 -0.8562784  -0.22807076]
 [ 0.86772811 -0.45724313 -0.78520433]]
original action [-1.84461121  1.14848484 -0.04831291 -0.21343162  0.1119903   1.25501524
 -0.75064099  0.09310896 -0.45614152 -1.57040867]
[ 1.34310091 -2.90048311  1.56000384  1.29459519 -2.54663131  0.59415735
 -2.63657495 -0.67251466 -2.05517837  2.72604826] [ 0.86702176 -6.61469667 -2.71766305 -5.07784914 -4.73413515  4.81837361
 -3.72058973  4.40069606 -6.85022722 -3.65794507]
(10,)
(10,)
[[ 1.40914951  1.32097198]
 [ 3.05162674 -6.62150911]
 [ 1.46125615 -1.97495366]
 [ 1.07518068 -4.38829013]
 [-2.80351602 -5.13769417]
 [ 0.86548154  5.42648393]
 [-2.8463776  -4.19605308]
 [-0.47514235  3.947446

(array([[ 0.44854622,  0.1651215 ],
        [ 0.97136296, -0.82768864],
        [ 0.46513228, -0.24686921],
        [ 0.34224064, -0.54853627],
        [-0.89238686, -0.64221177],
        [ 0.27549133,  0.67831049],
        [-0.90603013, -0.52450663],
        [-0.15124251,  0.49343076],
        [-0.77486077, -0.94779633],
        [ 0.81057971, -0.44884254]]),
 array([ -1.88249531, -12.78954249,  -3.17218355,  -4.25447745,
         -8.72654713,  -2.67627044,  -8.33636971,  -2.38889722,
         -8.91652749,  -8.77186154]))

In [1]:
from classes.environments.PendulumSimple import PendulumSimple
import numpy as np
env = PendulumSimple()
print(env.reset())
print(env.step([0.5]))

(array([-0.67713841,  0.02756482]), {})
[-0.67713841  0.02756482]
original action 1.0
-2.1272930519248825 0.2205185338256559
()
()
[[-2.14060878 -0.26631457]]
(array([-0.68137694, -0.03328932]), -4.531238571143943, False, False, {})


In [3]:
state_action = np.array([[ -0.67713841,  0.02756482, 0.5]])
print(state_action)
env.query_generator(state_action)

[[-0.67713841  0.02756482  0.5       ]]
original action [1.]
[-2.12729305] [0.22051856]
(1,)
(1,)
[[-2.14060878 -0.26631454]]


(array([[-0.68137694, -0.03328932]]), array([-0.45312386]))

In [6]:
env = PendulumSimple()
agent = FD_LSVI(env)
state_disc = 40
action_disc = 5
agent.get_datasets(disc_numbers=[state_disc, state_disc, action_disc])
agent.compute_q_values()

optimal design found: before squeezing 21.75177667567862, after squeezing 31.020218121595224
(296, 3)
(296, 20)
(296,)
(296, 2)
(5,)
step 19 done
step 18 done
step 17 done
step 16 done
step 15 done
step 14 done
step 13 done
step 12 done
step 11 done
step 10 done
step 9 done
step 8 done
step 7 done
step 6 done
step 5 done
step 4 done
step 3 done
step 2 done
step 1 done
step 0 done


In [7]:
agent.w_vectors[-7]

array([ 9.48791306e-03, -3.06048765e-03, -2.96137430e-01, -4.32042314e-03,
       -6.81454078e-03,  1.25321724e-02,  7.18952145e-03, -5.63145431e-03,
        5.40551356e-03, -1.33621286e-03,  1.05101530e-02, -2.95223948e-01,
        2.92146203e-03, -3.30402958e-04, -8.31735974e-03, -9.46615653e-04,
        2.65255627e+01, -6.44603907e-03, -7.06493668e-03,  4.66283530e-03])

In [8]:
state = env.reset()[0]
done = False
h = 0
episodic_return = 0

while not done:
    # action = env.action_space.sample()
    action = agent.choose_action(state, h)

    next_state, reward, terminated, truncated, _ = env.step(action)
    print('current state: {}, current action: {}, current reward: {}'.format(state, action, reward))
    inutile = input()
    episodic_return += reward

    done = terminated or truncated
    state = next_state
    h += 1

current state: [-0.06956029 -0.667235  ], current action: [0.], current reward: 0.9507042014385455
current state: [-0.08276746 -0.10372891], current action: [-0.5], current reward: 0.9911629049203963
current state: [-0.08987461 -0.05581938], current action: [-0.5], current reward: 0.9907163005092164
current state: [-0.09647603 -0.05184737], current action: [-0.5], current reward: 0.9895449293762895
current state: [-0.10325123 -0.05321241], current action: [-0.5], current reward: 0.9881950383379778
current state: [-0.11028984 -0.05528107], current action: [-0.5], current reward: 0.9866891624459231
current state: [-0.1176106  -0.05749712], current action: [-0.5], current reward: 0.9850175209153421
current state: [-0.12522376 -0.05979353], current action: [-0.5], current reward: 0.9831659586522937
current state: [-0.13313842 -0.06216164], current action: [-0.5], current reward: 0.9811188921659642
current state: [-0.14136346 -0.06459931], current action: [-0.5], current reward: 0.978859643

In [8]:
import numpy as np
x = 1355
((x + np.pi) % (2 * np.pi)) - np.pi

-2.168026350790523